spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  max-courses-per-student: 5
  max-students-per-course: 50

